version: '3.8'

services:
  app:
    image: 'pos-system'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lifepill
    depends_on:
      - db
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="Prami@3990"
      - SPRING_DATASOURCE_URL="jdbc:postgresql://db:5432/pos-monolithic"
      - SPRING_DATASOURCE_USERNAME="postgres"
      - SPRING_DATASOURCE_PASSWORD="Prami@3990"
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8081:8081

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="Prami@3990"
      - POSTGRES_DB="pos-monolithic"
    ports:
      - 5432:5432
