version: '3.8'

services:
  pos-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pos-monolithic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Prami@3990
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prami@3990
      POSTGRES_DB: pos-monolithic
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
