version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    image: pramithamj/lifepill-pos-system
    container_name: lifepill_pos
    ports:
      - "8079:8079"
    depends_on:
      - postgres
      - redis


volumes:
  postgres-data: